name:  CI

on:
 pull_request:
    branches: [develop, master]
 push:
    branches: [develop, master]
    
env:
  NODE_VERSION: '14.x'                                             # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ env.NODE_VERSION }}
       cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Do Code Analysis
      run: echo "Do code analysis here..."

    - name: Upload Code coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: codeanalysis_coverage
      #   path: codecoverage
      run: echo "Upload code analysis coverage here..."

    - name: Run Tests
      run: npm run test

    - name: Upload Test coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: test_coverage
      #   path: testcoverage
      run: echo "Upload test coverage here..."
        
    - name: Build project
      if: github.event_name == 'push'
      run: echo "Build the project here..."

    - name: Upload Build folder as Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
        
    - name: Add Build Assets for Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: zip -r build.zip build


    - name: Create a Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Automated Issue from workflow
        token: ${{secrets.SEMANTIC_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: This issue was automatically created by GitHub workflow ${{github.sha}}   
  
      
  deploy-staging:
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url:  https://stagingdeploy.azurewebsites.net         # set application url

    steps:
    - name: Deploy to Staging Server
      run: echo "Deploy build to staging here..."
      
    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Automated Issue from staging deploy
        token: ${{secrets.SEMANTIC_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: This issue was automatically created by GitHub Staging deploy ${{github.sha}}
      
  deploy-production:
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url:  https://productiondeploy.azurewebsites.net         # set application url

    steps:
    - name: Deploy to Production Server
      run: echo "Deploy build to production here..."
      
    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Automated Issue from Production deploy
        token: ${{secrets.SEMANTIC_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: This issue was automatically created by GitHub Production deploy ${{github.sha}}
      
   
